version: '3'
services:
  nats:
    image: "nats"
    ports:
      - "4222:4222"
      - "6222:6222"
      - "8222:8222"
    command: -m 8222 --user test --pass p@ssword123
  nats-streaming:
    image: "nats-streaming"
    ports:
      - "4223:4223"
      - "8223:8223"
    command: -p 4223 -m 8223 --user test --pass p@ssword123